# Generated by Django 3.1.3 on 2021-01-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='description',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
