# Generated by Django 3.1.3 on 2021-01-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210122_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
